AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: The AuditEvent builder stack

# Add Resources Here: uncomment the following lines
Parameters:
  CredentialSubjectFunctionName:
    Type: String
    Description: Name of Credential Subject function
  EpochTimeName:
    Type: String
    Description: Name of Epoch time function
  CredentialSubjectFunctionArn:
    Type: String
    Description: Arn of Credential Subject function
  EpochTimeArn:
    Type: String
    Description: Arn of Epoch time function
  EventBusName:
    Type: String
    Description: The EventBus Name
  EventBusState:
    Type: String
    Description: The state of rule i.e Enabled or Disabled
    Default: DISABLED
  EventSource:
    Type: String
    Description: The Event bus source
  PermissionsBoundary:
    Type: String
    Default: ""
Conditions:
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, ""]]
Resources:
  AuditEventResponseReceivedRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      Description: Capture the audit event RESPONSE_RECEIVED
      State: !Ref EventBusState
      EventPattern:
        source:
          - !Ref EventSource
        detail-type:
          - RESPONSE_RECEIVED
      Targets:
        - Arn: !Ref AuditEventBuilderStateMachine
          Id: AuditEventBuilderStateMachineResponseReceivedEventTarget
          RoleArn: !GetAtt EventBridgeStateMachineExecutionRole.Arn
  AuditEventRequestSentRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      Description: Capture the audit event REQUEST_SENT
      State: !Ref EventBusState
      EventPattern:
        source:
          - !Ref EventSource
        detail-type:
          - REQUEST_SENT
      Targets:
        - Arn: !Ref AuditEventBuilderStateMachine
          Id: AuditEventBuilderStateMachineRequestSentEventTarget
          RoleArn: !GetAtt EventBridgeStateMachineExecutionRole.Arn
  AuditEventVcIssuedRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      Description: Capture the audit event VC_ISSUED
      State: !Ref EventBusState
      EventPattern:
        source:
          - !Ref EventSource
        detail-type:
          - VC_ISSUED
      Targets:
        - Arn: !Ref AuditEventBuilderStateMachine
          Id: AuditEventBuilderStateMachineVcIssuedTarget
          RoleArn: !GetAtt EventBridgeStateMachineExecutionRole.Arn
  AuditEventEndRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      Description: Capture the END event
      State: !Ref EventBusState
      EventPattern:
        source:
          - !Ref EventSource
        detail-type:
          - END
      Targets:
        - Arn: !Ref AuditEventBuilderStateMachine
          Id: AuditEventBuilderStateMachineEndTarget
          RoleArn: !GetAtt EventBridgeStateMachineExecutionRole.Arn
  AuditEventAbandonedRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      Description: Capture the ABANDONED event
      State: !Ref EventBusState
      EventPattern:
        source:
          - !Ref EventSource
        detail-type:
          - ABANDONED
      Targets:
        - Arn: !Ref AuditEventBuilderStateMachine
          Id: AuditEventBuilderStateMachineAbandonedEventTarget
          RoleArn: !GetAtt EventBridgeStateMachineExecutionRole.Arn

  EventBridgeStateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
      Policies:
        - PolicyName: EventBridgeStateMachineExecutionStartExecutionPolicy
          PolicyDocument:
            Statement:
              - Action: states:StartExecution
                Effect: Allow
                Resource: !Ref AuditEventBuilderStateMachine

  AuditEventBuilderStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      DefinitionUri: ../step-functions/audit_event_builder.asl.json
      DefinitionSubstitutions:
        CredentialSubjectFunctionArn: !Ref CredentialSubjectFunctionArn
        EpochTimeArn: !Ref EpochTimeArn
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt AuditEventBuilderStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref CredentialSubjectFunctionName
        - LambdaInvokePolicy:
            FunctionName: !Ref EpochTimeName
        - Statement:
            Effect: Allow
            Action: logs:*
            Resource: "*"
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  AuditEventBuilderStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${AWS::StackName}-audit_event_builder-state-machine-logs
      RetentionInDays: 7
