name: Check PR

on: pull_request
permissions: read-all

concurrency:
  group: check-pr-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Run tests
    uses: ./.github/workflows/unit-tests.yml

  sonarcloud:
    name: SonarCloud
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Run a SonarCloud scan
        uses: govuk-one-login/github-actions/code-quality/sonarcloud@oj-1984-add-codeql-action
        with:
          coverage-artifact: ${{ needs.unit-tests.outputs.coverage-artifact }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Run a CodeQL scan
        uses: govuk-one-login/github-actions/code-quality/codeql@oj-1984-add-codeql-action
        with:
          languages: javascript-typescript

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Run pre-commit
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@df9647d3b26270963a3c013feee09b0e72887795
        with:
          all-files: true
