name: Check PR

on: pull_request
permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    concurrency:
      group: pre-commit-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Run pre-commit
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@e6b6ed890b35904e1be79f7f35ffec983fa4d9db
        with:
          all-files: true

  unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      coverage-report: true

  mocked-tests:
    name: Run tests
    uses: ./.github/workflows/run-mocked-tests.yml

  deploy:
    name: Preview
    uses: ./.github/workflows/deploy-branch.yml
    permissions:
      id-token: write
      contents: read

  aws-tests:
    name: Run tests
    needs: deploy
    uses: ./.github/workflows/run-aws-tests.yml
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      aws-region: ${{ needs.deploy.outputs.aws-region }}
