name: TypeScript Unit Tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  get-lambdas:
    runs-on: ubuntu-latest
    outputs:
      names: ${{steps.getNames.outputs.names}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get all lambda names
        id: getNames
        run: |
          names=""
          for dir in lambdas/*/
          do
              names+=\"$(basename -- "$dir")\",
          done
          echo names={\"lambdas\": [${names%,}]} >> "$GITHUB_OUTPUT"

  run-lambda-unit-tests:
    runs-on: ubuntu-latest
    needs: get-lambdas
    strategy:
      matrix: ${{ fromJSON(needs.get-lambdas.outputs.names) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Change directories
        run: cd lambdas/${{ matrix.lambda }}
      - name: Install Dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run Tests
        run: npm run test
