name: pre-commit

on: workflow_call
permissions: {}

concurrency:
  group: pre-commit-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"

      - name: Run hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: "--all-files"
