name: Unit tests

on: workflow_call
permissions: read-all

concurrency:
  group: unit-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  run-unit-tests:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run coverage

      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          retention-days: 3
          path: coverage
