name: Mocked tests

on:
  workflow_call:

concurrency:
  group: mocked-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  run-tests:
    name: Mocked
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci --include-workspace-root

      - name: Run tests
        uses: govuk-one-login/github-actions/node/run-script@e6b6ed890b35904e1be79f7f35ffec983fa4d9db
        with:
          working-directory: integration-tests
          script: npm run test:sfn:mocked -- --config jest.config.ci.ts
